### ISSUE TITLE
Getting Notification to install TeaCode even after it's installed.

### ISSUE THREAD

**Issue by macsavers** [Apptorium/TeaCode-Atom-Extension#2]
![screen shot 2018-11-06 at 3 00 53 pm](https://user-images.githubusercontent.com/422624/48093559-4bc0a480-e1d5-11e8-9e71-c1a29a1bdec6.png)

The screenshot shows the plugin is installed with the notification still showing the error.

Any ideas? It's clearly installed, but it won't work. I get the error every time.

**Comment by ghost** [comment]
@macsavers which macOS & TeaCode version are you running? I'm having similar issues.

**Comment by macsavers** [comment]
Mojave and the latest TeaCode. I just installed it.

I had to use control + command + e instead of shift + command + e.
